package Logic;

public enum GameState {
    WALK, BAITING, FISHING, AFTERFISHING , LOADING ,
    LOADED, MENU ,NEW_GAME, LOAD_GAME, OPTIONM, OPTIONP,
    EXIT , PAUSE ,SAVE ,RESUME , FISHRAISING, LISTOFISH
}
